# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog of Polyarniy Nikolay
email: PolarNick239@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal blog about computer vision, GPU coding and other stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://polarnick239.github.io" # the base hostname & protocol for your site
github_username:  PolarNick239
vk_username:  PolarNick

# Build settings
markdown: kramdown
highlighter: rouge
source: .
exclude: [src]

kramdown:
  input: GFM
  hard_wrap: false
